steps:
#this step builds the container image.
  - name: "gcr.io/cloud-builders/docker"
    id: build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-tests-tucker:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-test-tucker:latest"
      







---